### ISSUE TITLE
adding miniboxing annotation makes tailrec fail

### ISSUE THREAD

**Issue by julien-truffaut** [miniboxing/miniboxing-plugin#181]
I implemented a very basic linked list and then tried to use miniboxing to see the performance boost. However, all methods with a tailrec annotations produce the following error once I added the miniboxing annotation:

```
Error:(29, 50) could not optimize @tailrec annotated method drop: it contains a recursive call not in tail position
  @tailrec final def drop(n: Int): ConsList[A] = this match {
                                                 ^
```

Here is a link to the implementation: https://github.com/julien-truffaut/brique/blob/miniboxing/core/src/main/scala/brique/ConsList.scala#L35

Just to be clear, tailrec was working perfectly well before I added the miniboxing annotation.

**Comment by VladUreche** [comment]
Thanks for the report @julien-truffaut -- looking into the bug now.

**Comment by VladUreche** [comment]
# The Problem

The underlying error is obscured by the tailcalls tranformation in the scala compile, but following the fix, will be reported by miniboxing:

``` scala
$ cat gh-bug-181-workaround-before.scala 
package miniboxing.tests.bug181
import annotation.tailrec

// Thanks to @julien-truffaut for spotting this bug in his `brique`
// project: https://github.com/julien-truffaut/brique

class ConsList[@miniboxed A] {
  @tailrec final def dropWhile(p: A => Boolean): ConsList[A] = this match {
    case Cons(h,t) => if (p(h)) t.dropWhile(p) else this
    case CNil()    => this
  }
}

case class Cons[@miniboxed A](val head: A, val tail: ConsList[A]) extends ConsList[A]
case class CNil[@miniboxed A]() extends ConsList[A]
```

and you compile it and get:

``` scala
$ mb-scalac gh-bug-181-workaround-before.scala 
gh-bug-181-workaround-before.scala:8: error: Following the miniboxing transformation,
this method will no longer be in tailcall position (please see 
https://github.com/miniboxing/miniboxing-plugin/issues/181 for a workaround):
  @tailrec final def dropWhile(p: A => Boolean): ConsList[A] = this match {
                     ^
one error found
```

# The Solution (er, workaround)

The workaround is simple.  You can create a tail-recursive internal method `dropWhileInternal`, and call it from the `dropWhile` method: 

``` scala
$ cat gh-bug-181-workaround-after.scala 
...
class ConsList[@miniboxed A] {
  final def dropWhile(p: A => Boolean): ConsList[A] = {
    @tailrec def dropWhileInternal(lst: ConsList[A]): ConsList[A] =
      this match {
        case Cons(h,t) => if (p(h)) dropWhileInternal(t) else this
        case CNil()    => this
      }
    dropWhileInternal(this)
  }
}
...
```

Notice the `tailrec` annotated method is now the internal method, while the external method doesn't even need to be final anymore. This way, your program will compile correctly:

```
$ mb-scalac gh-bug-181-workaround-after.scala # no error
```

That's it! If you want to learn why this occurs, follow on.

# The Details

Let us take a simpler example, so we can follow the code:

``` scala
$ cat gh-bug-181r.scala 
package miniboxing.tests.bug181.reduced
import annotation.tailrec

// Thanks to @julien-truffaut for spotting this bug in his `brique`
// project: https://github.com/julien-truffaut/brique

class ConsList[@miniboxed A] {
  def tail: ConsList[A] = ???
  @tailrec final def drop(): ConsList[A] = tail.drop()
}

$ mb-scalac gh-bug-181r.scala
gh-bug-181r.scala:9: error: Following the miniboxing transformation, this method will no longer be in tailcall position (please see https://github.com/miniboxing/miniboxing-plugin/issues/181 for a workaround):
  @tailrec final def drop(): ConsList[A] = tail.drop()
                     ^
one error found
```

Why does the error occur? We can print the internal compiler view of the program before and after the miniboxing transformation. The `uncurry` phase is the one just before the miniboxing transformation and the `minibox-commit` is the last phase of the miniboxing transformation:

```
$ mb-scalac gh-bug-181r.scala -Xprint:uncurry,minibox-commit

[[syntax trees at end of                   uncurry]] // gh-bug-181r.scala
package miniboxing.tests.bug181.reduced {
  class ConsList[@miniboxed A] extends Object {
    ...
    def tail(): ConsList[A] = ???();
    @tailrec final def drop(): ConsList[A] = tail().drop()
  }
}

[[syntax trees at end of            minibox-commit]] // gh-bug-181r.scala
package miniboxing.tests.bug181.reduced {
  abstract trait ConsList[@miniboxed A] extends Object {
    def tail(): ConsList[A];
    final def drop(): ConsList[A]
  };
  class ConsList_D[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  };
  class ConsList_J[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  };
  class ConsList_L[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  }
}

gh-bug-181r.scala:9: error: could not optimize @tailrec annotated method drop: it contains a recursive call targeting a supertype
  @tailrec final def drop(): ConsList[A] = tail.drop()
                     ^
one error found
```

So, miniboxing transforms the `ConsList` class in four elements:
- the `ConsList` interface, which only contains method declarations
- three versions of the `ConsList` class:
  - `ConsList_L` for objects (e.g. `String`)
  - `ConsList_J` for integral primitive types (e.g. `Int`, `Byte`, `Long`)
  - `ConsList_D` for floating-point primitive types (e.g. `Float`, `Double`)

Now, in any of these classes we have two methods:
- `tail`, which returns a `ConsList` (the interface)
- `drop` the previously tail-recursive method

```
  class ConsList_J[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  };
```

The problem is that now there are three versions of the `drop` method, each in its own separate class: `drop` in `ConsList_L`, `drop` in `ConsList_J` and `drop` in `ConsList_D`, with potentially different codes. And calling `tail()` does not guarantee one of the classes, **but only "promises" the interface `ConsList`**. Therefore, in `tail().drop()`, `drop()` might no longer mean the current class' `drop()` method, but another class' version => it's no longer in tail call position!

# Notice

If you've been using specialization, you might be wondering why miniboxing would impose such restrictions on your code. The answer is correctness -- see https://issues.scala-lang.org/browse/SI-9180 for what can happen to specialization :-1:

**Comment by julien-truffaut** [comment]
Thanks @VladUreche for the quick feedback

**Comment by VladUreche** [comment]
# The Problem

The underlying error is obscured by the tailcalls tranformation in the scala compile, but following the fix, will be reported by miniboxing:

```scala
$ cat gh-bug-181-workaround-before.scala 
package miniboxing.tests.bug181
import annotation.tailrec

// Thanks to @julien-truffaut for spotting this bug in his `brique`
// project: https://github.com/julien-truffaut/brique

class ConsList[@miniboxed A] {
  @tailrec final def dropWhile(p: A => Boolean): ConsList[A] = this match {
    case Cons(h,t) => if (p(h)) t.dropWhile(p) else this
    case CNil()    => this
  }
}

case class Cons[@miniboxed A](val head: A, val tail: ConsList[A]) extends ConsList[A]
case class CNil[@miniboxed A]() extends ConsList[A]
```

and you compile it and get:

```scala
$ mb-scalac gh-bug-181-workaround-before.scala 
gh-bug-181-workaround-before.scala:8: error: Following the miniboxing transformation,
this method will no longer be in tailcall position (please see 
https://github.com/miniboxing/miniboxing-plugin/issues/181 for a workaround):
  @tailrec final def dropWhile(p: A => Boolean): ConsList[A] = this match {
                     ^
one error found
```

# The Solution (er, workaround)

The workaround is simple.  You can create a tail-recursive internal method `dropWhileInternal`, and call it from the `dropWhile` method: 

```scala
$ cat gh-bug-181-workaround-after.scala 
...
class ConsList[@miniboxed A] {
  final def dropWhile(p: A => Boolean): ConsList[A] = {
    @tailrec def dropWhileInternal(lst: ConsList[A]): ConsList[A] =
      this match {
        case Cons(h,t) => if (p(h)) dropWhileInternal(t) else this
        case CNil()    => this
      }
    dropWhileInternal(this)
  }
}
...
```

Notice the `tailrec` annotated method is now the internal method, while the external method doesn't even need to be final anymore. This way, your program will compile correctly:

```
$ mb-scalac gh-bug-181-workaround-after.scala # no error
```

That's it! If you want to learn why this occurs, follow on.

# The Details

Let us take a simpler example, so we can follow the code:

```scala
$ cat gh-bug-181r.scala 
package miniboxing.tests.bug181.reduced
import annotation.tailrec

// Thanks to @julien-truffaut for spotting this bug in his `brique`
// project: https://github.com/julien-truffaut/brique

class ConsList[@miniboxed A] {
  def tail: ConsList[A] = ???
  @tailrec final def drop(): ConsList[A] = tail.drop()
}

$ mb-scalac gh-bug-181r.scala
gh-bug-181r.scala:9: error: Following the miniboxing transformation, this method will no longer be in tailcall position (please see https://github.com/miniboxing/miniboxing-plugin/issues/181 for a workaround):
  @tailrec final def drop(): ConsList[A] = tail.drop()
                     ^
one error found
```

Why does the error occur? We can print the internal compiler view of the program before and after the miniboxing transformation. The `uncurry` phase is the one just before the miniboxing transformation and the `minibox-commit` is the last phase of the miniboxing transformation:

```
$ mb-scalac gh-bug-181r.scala -Xprint:uncurry,minibox-commit

[[syntax trees at end of                   uncurry]] // gh-bug-181r.scala
package miniboxing.tests.bug181.reduced {
  class ConsList[@miniboxed A] extends Object {
    ...
    def tail(): ConsList[A] = ???();
    @tailrec final def drop(): ConsList[A] = tail().drop()
  }
}

[[syntax trees at end of            minibox-commit]] // gh-bug-181r.scala
package miniboxing.tests.bug181.reduced {
  abstract trait ConsList[@miniboxed A] extends Object {
    def tail(): ConsList[A];
    final def drop(): ConsList[A]
  };
  class ConsList_D[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  };
  class ConsList_J[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  };
  class ConsList_L[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  }
}

gh-bug-181r.scala:9: error: could not optimize @tailrec annotated method drop: it contains a recursive call targeting a supertype
  @tailrec final def drop(): ConsList[A] = tail.drop()
                     ^
one error found
```

So, miniboxing transforms the `ConsList` class in four elements:
 * the `ConsList` interface, which only contains method declarations
 * three versions of the `ConsList` class:
   * `ConsList_L` for objects (e.g. `String`)
   * `ConsList_J` for integral primitive types (e.g. `Int`, `Byte`, `Long`)
   * `ConsList_D` for floating-point primitive types (e.g. `Float`, `Double`)

Now, in any of these classes we have two methods:
 * `tail`, which returns a `ConsList` (the interface)
 * `drop` the previously tail-recursive method

```
  class ConsList_J[Asp] extends Object with ConsList[Asp] {
    ...
    def tail(): ConsList[Asp] = ???();
    @tailrec final def drop(): ConsList[Asp] = tail().drop()
  };
```

The problem is that now there are three versions of the `drop` method, each in its own separate class: `drop` in `ConsList_L`, `drop` in `ConsList_J` and `drop` in `ConsList_D`, with potentially different codes. And calling `tail()` does not guarantee one of the classes, **but only "promises" the interface `ConsList`**. Therefore, in `tail().drop()`, `drop()` might no longer mean the current class' `drop()` method, but another class' version => it's no longer in tail call position!

# Notice

If you've been using specialization, you might be wondering why miniboxing impose such restrictions on your code. The answer is correctness -- see https://issues.scala-lang.org/browse/SI-9180 for what can happen to specialization :-1:

**Comment by VladUreche** [comment]
@julien-truffaut: Do you need any help with refactoring your collections to use the workaround?

**Comment by julien-truffaut** [comment]
Thank @VladUreche for the workaround, I should be able to implement it easily.

I have a few questions if you don't mind:
-  why `tail` of `ConsList_J` returns a `ConsList` and not a `ConsList_J` (this is applicable to other methods and `ConsList_X`)? wouldn't it solve the ambiguity of recursive methods?
-  do you know if using an internal method has an impact of performance?

**Comment by VladUreche** [comment]
> why `tail` of `ConsList_J` returns a `ConsList` and not a `ConsList_J`

The problem is that we cannot statically guarantee that any `ConsList[Int]` is in fact a `ConsList_J` (and, as the example below shows, this is not always the case):

``` scala
$ mb-scala -2.10
Welcome to Scala version 2.10.4-20140209-180020-b66a39653b (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_76).
Type in expressions to have them evaluated.
Type :help for more information.

scala> class ConsList[@miniboxed T]
defined class ConsList

scala> def newConsList[T] = new ConsList[T]
<console>:8: warning: The following code could benefit from miniboxing specialization if the type parameter T of method newConsList would be marked as "@miniboxed T" (it would be used to instantiate miniboxed type parameter T of class ConsList)
       def newConsList[T] = new ConsList[T]
                            ^
newConsList: [T]=> ConsList[T]

scala> val cons1 = new ConsList[Int] // result is indeed a ConsList_J
cons1: ConsList[Int] = ConsList_J@cd8658e

scala> val cons2 = newConsList[Int] // result is a ConsList_L
<console>:9: warning: The method newConsList would benefit from miniboxing type parameter T, since it is instantiated by a primitive type.
       val cons2 = newConsList[Int]
                              ^
cons2: ConsList[Int] = ConsList_L@50db6129
```

(note: bug #180 is preventing this example from running in the 2.11.5 REPL)

Notice the two values:

``` scala
cons1: ConsList[Int] = ConsList_J@cd8658e
cons2: ConsList[Int] = ConsList_L@50db6129
```

As you can see, the miniboxing plugin will _warn twice_ that the code is suboptimal, trying to avoid the case where `ConsList[Int]` is instantiated by a `ConsList_L` at runtime. However, it will not completely prevent this, as many programs written in Scala are using this pattern, so it would prevent them from compiling. Thus, instead, it focuses on correctness, falling back to the common parent of `ConsList_J` and `ConsList_L`: `interface ConsList`.

> (this is applicable to other methods and `ConsList_X`)? wouldn't it solve the ambiguity of recursive methods?

Yes, no method can make stronger promisses than just `ConsList[X]`. And yes, if you could statically guarantee all values of type `ConsList[Int]` are instantiated by `ConsList_J` that would prevent the 
ambiguity.

As an aside, the path taken by Java specialization ([Project Valhalla](http://openjdk.java.net/projects/valhalla/)) is going down this very strict path where `ConsList<int>` means the specialized version of `ConsList` -- and it's going to break many patterns in Scala. I will be presenting this at [ScalaDays 2015 in SF](http://event.scaladays.org/scaladays-sanfran-2015#!#schedulePopupExtras-6538).

**Comment by VladUreche** [comment]
>  do you know if using an internal method has an impact of performance?

It should not impact the performace at all. Sorry for missing that in the first message.

**Comment by julien-truffaut** [comment]
Thanks for the answer, I think I got your point. I am looking forward to watch your presentation.

**Comment by VladUreche** [comment]
@julien-truffaut don't hesitate to ask any questions that pop up along the way!
