### ISSUE TITLE
Implicit value class bug

### ISSUE THREAD

**Issue by ctongfei** [miniboxing/miniboxing-plugin#191]
``` scala
object Test2 {

  implicit class RichX[@miniboxed X](val x: X) extends AnyVal {
    def f = 0
  }

  def main(args: Array[String]) = {
    val i = 0
    print(i.f)
  }
}
```

Compiling this results in

```
Error:scalac: Error: value class parameter must be a val and not be private[this]
scala.reflect.internal.Types$TypeError: value class parameter must be a val and not be private[this]
```

This code compiles after deleting the `@miniboxed` annotation.

**Comment by VladUreche** [comment]
@ctongfei, value classes cannot be specialized (or miniboxed). This is a fundemental limitation of opportunistic specialization -- it relies on virtual method dispatch in order to function, while value classes replace virtual method dispatch by static dispatch (extension methods). I will issue an error when this occurs.
